kind: Deployment
apiVersion: apps/v1
metadata:
  name: express-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: express-api
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
      restartPolicy: Always

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
    - host: express-api.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: express-api
                port:
                  number: 3000

---

kind: Service
apiVersion: v1
metadata:
  name: express-api
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 32002
  selector:
    app: express-api